package export

import (
	"context"
	"fmt"
	"time"

	"github.com/bmcelhaney/insight-forge/internal/db"
	"github.com/bmcelhaney/insight-forge/internal/models"
	"github.com/xuri/excelize/v2"
)

// GenerateExcelBundle creates a multi-sheet Excel file with all evidence for an NSN.
// Sheets:
// 1. Summary - viability, risk, executive summary, scores
// 2. Snapshots - all raw source data captured
// 3. Flags & Risks - detailed flags
// 4. Demand & Suppliers - ecosystem view
// 5. Audit - when it was generated, sources used
func GenerateExcelBundle(ctx context.Context, database *db.DB, nsn string) (*excelize.File, error) {
	f := excelize.NewFile()

	result, err := database.GetLatestResult(ctx, nsn)
	if err != nil {
		// Still generate file with "no data" note
		result = models.InsightResult{EntityID: nsn}
	}

	snapshots, _ := database.GetSnapshots(ctx, nsn)

	// ========== Sheet 1: Executive Summary ==========
	sheet1 := "Executive Summary"
	f.SetSheetName("Sheet1", sheet1)

	f.SetCellValue(sheet1, "A1", "INSIGHT FORGE - NSN INTELLIGENCE REPORT")
	f.SetCellValue(sheet1, "A2", fmt.Sprintf("Generated: %s", time.Now().Format(time.RFC3339)))
	f.SetCellValue(sheet1, "A4", "NSN")
	f.SetCellValue(sheet1, "B4", nsn)
	f.SetCellValue(sheet1, "A5", "Viability Score")
	f.SetCellValue(sheet1, "B5", result.ViabilityScore)
	f.SetCellValue(sheet1, "A6", "Risk Score")
	f.SetCellValue(sheet1, "B6", result.RiskScore)
	f.SetCellValue(sheet1, "A8", "Executive Summary")
	f.SetCellValue(sheet1, "A9", result.Summary)

	// Style header
	headerStyle, _ := f.NewStyle(&excelize.Style{Font: &excelize.Font{Bold: true, Size: 14}})
	f.SetCellStyle(sheet1, "A1", "A1", headerStyle)

	// ========== Sheet 2: Source Snapshots ==========
	sheet2 := "Source Snapshots"
	f.NewSheet(sheet2)

	f.SetCellValue(sheet2, "A1", "Source")
	f.SetCellValue(sheet2, "B1", "Captured At")
	f.SetCellValue(sheet2, "C1", "Quality Score")
	f.SetCellValue(sheet2, "D1", "Key Data")

	for i, s := range snapshots {
		row := i + 2
		f.SetCellValue(sheet2, fmt.Sprintf("A%d", row), s.SourceCode)
		f.SetCellValue(sheet2, fmt.Sprintf("B%d", row), s.SnapshotAt.Format(time.RFC3339))
		f.SetCellValue(sheet2, fmt.Sprintf("C%d", row), s.QualityScore)
		// Flatten a bit of the raw response
		f.SetCellValue(sheet2, fmt.Sprintf("D%d", row), fmt.Sprintf("%v", s.RawResponse))
	}

	// ========== Sheet 3: Flags & Risks ==========
	sheet3 := "Flags & Risks"
	f.NewSheet(sheet3)

	f.SetCellValue(sheet3, "A1", "Type")
	f.SetCellValue(sheet3, "B1", "Severity")
	f.SetCellValue(sheet3, "C1", "Description")
	f.SetCellValue(sheet3, "D1", "Sources")

	for i, flag := range result.Flags {
		row := i + 2
		f.SetCellValue(sheet3, fmt.Sprintf("A%d", row), flag.Type)
		f.SetCellValue(sheet3, fmt.Sprintf("B%d", row), flag.Severity)
		f.SetCellValue(sheet3, fmt.Sprintf("C%d", row), flag.Description)
		f.SetCellValue(sheet3, fmt.Sprintf("D%d", row), fmt.Sprintf("%v", flag.SourceCodes))
	}

	// ========== Sheet 4: Demand & Suppliers ==========
	sheet4 := "Demand & Suppliers"
	f.NewSheet(sheet4)

	f.SetCellValue(sheet4, "A1", "Metric")
	f.SetCellValue(sheet4, "B1", "Value")

	f.SetCellValue(sheet4, "A2", "Total Awards")
	f.SetCellValue(sheet4, "B2", result.DemandSignals.TotalAwards)
	f.SetCellValue(sheet4, "A3", "Total Value (USD)")
	f.SetCellValue(sheet4, "B3", result.DemandSignals.TotalValueUSD)
	f.SetCellValue(sheet4, "A4", "Top Agencies")
	f.SetCellValue(sheet4, "B4", fmt.Sprintf("%v", result.DemandSignals.TopAgencies))
	f.SetCellValue(sheet4, "A5", "Trend")
	f.SetCellValue(sheet4, "B5", result.DemandSignals.RecentTrend)

	f.SetCellValue(sheet4, "A7", "Supplier Concentration Risk")
	f.SetCellValue(sheet4, "B7", result.SupplierData.ConcentrationRisk)
	f.SetCellValue(sheet4, "A8", "Total Suppliers")
	f.SetCellValue(sheet4, "B8", result.SupplierData.TotalSuppliers)
	f.SetCellValue(sheet4, "A9", "Primary Countries")
	f.SetCellValue(sheet4, "B9", fmt.Sprintf("%v", result.SupplierData.PrimaryCountries))

	// ========== Sheet 5: Audit & Provenance ==========
	sheet5 := "Audit & Provenance"
	f.NewSheet(sheet5)

	f.SetCellValue(sheet5, "A1", "Field")
	f.SetCellValue(sheet5, "B1", "Value")

	f.SetCellValue(sheet5, "A2", "NSN / Entity")
	f.SetCellValue(sheet5, "B2", nsn)
	f.SetCellValue(sheet5, "A3", "Generated At")
	f.SetCellValue(sheet5, "B3", result.GeneratedAt.Format(time.RFC3339))
	f.SetCellValue(sheet5, "A4", "Generated By")
	f.SetCellValue(sheet5, "B4", result.GeneratedBy)
	f.SetCellValue(sheet5, "A5", "Sources Used")
	f.SetCellValue(sheet5, "B5", fmt.Sprintf("%d snapshots", len(snapshots)))
	f.SetCellValue(sheet5, "A6", "Based On Snapshot IDs")
	f.SetCellValue(sheet5, "B6", fmt.Sprintf("%v", result.BasedOnSnapshotIDs))
	f.SetCellValue(sheet5, "A8", "Note")
	f.SetCellValue(sheet5, "A9", "This is a prototype export from Insight Forge running on nib-sprite.")
	f.SetCellValue(sheet5, "A10", "Data is for evaluation only. Real production version will include full provenance and cryptographic signing.")

	// Set active sheet and return
	f.SetActiveSheet(1)
	return f, nil
}
